jwt:
    issuer: under912@naver.com
    secret: nhJoeH7FctPVlEKToZJw3hjF609SJDSE
logging:
    file:
        name: /logs/ch10.log
    level:
        jdbc:
            sqlonly: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        resultsettable: debug
        root: info
        sqltiming: debug
server:
    port: 8080
    servlet:
        context-path: /ch10
spring:
    application:
        name: ch10
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/studydb
        username: root
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
